# Generated by Django 3.0.2 on 2020-01-15 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200115_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'Only valid mobile number is allowed.')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_number',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numerical characters are allowed.'), django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ssn',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numerical characters are allowed.'), django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
