# Generated by Django 3.0.2 on 2020-01-15 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200115_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='personal_number',
            field=models.CharField(editable=False, max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numerical characters are allowed.'), django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
    ]
